version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: banco-teste-deploy
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ellecj
      MYSQL_USER: ellecj
      MYSQL_PASSWORD: 'c6XBnshOfrUAe?a_'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_net

  wordpress:
    image: wordpress:latest
    container_name: teste-deploy
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ellecj
      WORDPRESS_DB_PASSWORD: 'c6XBnshOfrUAe?a_'
      WORDPRESS_DB_NAME: ellecj
    volumes:
      - ./wp-content:/var/www/html/wp-content      # wp-content mapeado corretamente
      - .:/var/www/html                            # Diretório atual mapeado corretamente
    networks:
      - wordpress_net

volumes:
  db_data:

networks:
  wordpress_net:
    driver: bridge
