version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: banco-teste-deploy
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ellecj      # Mesmo nome do banco no wp-config.php
      MYSQL_USER: ellecj          # Mesmo usuário do banco no wp-config.php
      MYSQL_PASSWORD: 'c6XBnshOfrUAe?a_'  # Mesmo password do banco no wp-config.php
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
      - ./deploy-scripts:/var/www/html/deploy-scripts
    networks:
      - wordpress_net

  wordpress:
    image: wordpress:latest
    container_name: teste-deploy
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ellecj
      WORDPRESS_DB_PASSWORD: 'c6XBnshOfrUAe?a_'
      WORDPRESS_DB_NAME: ellecj
    volumes:
      - ./wp-content:/var/www/html/wp-content
       - .:/var/www/html
    networks:
      - wordpress_net

volumes:
  db_data:

networks:
  wordpress_net:
    driver: bridge